<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <UseWindowsForms>true</UseWindowsForms>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.4"/>
        <PackageReference Include="Avalonia.Desktop" Version="12.0.4"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.2">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Common" Version="8.4.2" />
        <PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.2" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="Irihi.Ursa" Version="2.0.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
        <PackageReference Include="OpenCvSharp4.Extensions" Version="4.13.0.20260602" />
        <PackageReference Include="OpenCvSharp4.Windows" Version="4.13.0.20260602" />
        <PackageReference Include="ReactiveUI" Version="23.2.28" />
        <PackageReference Include="ReactiveUI.Avalonia" Version="12.0.3" />
        <PackageReference Include="ReactiveUI.SourceGenerators" Version="3.1.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="HotAvalonia" Version="3.1.1" PrivateAssets="All" Publish="True" />
        <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="12.0.4" PrivateAssets="All" Publish="True" />
        <PackageReference Include="Semi.Avalonia" Version="12.0.3" />
        <PackageReference Include="Serilog" Version="4.3.1" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\Windows\MainWindow.axaml.cs">
        <DependentUpon>MainWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Page\HomePage.axaml.cs">
        <DependentUpon>HomePageView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Page\SettingsPage.axaml.cs">
        <DependentUpon>SettingsPage.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
